name: Test Build

on:
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: use nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          echo ">>> $SUPER_SECRET"
          echo ">>> ${{ secrets.DOCKERHUB_USERNAME }}"
          echo ">>> $USERNAME"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
