name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: use nodejs
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: build-vue
      run: |
        cd file-online-manager-web
        npm install
        npm run build
    - name: Build the Docker image
      run: |
        cd ..
        docker build . --file Dockerfile --tag file-manage:$(date +%s)
